CREATE TABLE produto
(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR2(150) NOT NULL,
    descricao    TEXT,
    preco        NUMBER(10,2) NOT NULL,
    imagem_url   VARCHAR2(255),
    FOREIGN KEY (categoria_id) REFERENCES categoria (id)
);

CREATE TABLE usuario
(
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE,
    senha VARCHAR2(255) NOT NULL,
    role  VARCHAR2(20) DEFAULT 'CLIENTE'
);

CREATE TABLE endereco
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  NUMBER NOT NULL,
    logradouro  VARCHAR2(255),
    numero      VARCHAR2(10),
    complemento VARCHAR2(100),
    bairro      VARCHAR2(100),
    cidade      VARCHAR2(100),
    estado      VARCHAR2(2),
    cep         VARCHAR2(10),
    FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE TABLE pedido
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  NUMBER NOT NULL,
    data_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status      VARCHAR2(20) DEFAULT 'PENDENTE',
    valor_total NUMBER(10,2),
    endereco_id NUMBER,
    FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    FOREIGN KEY (endereco_id) REFERENCES endereco (id)
);

CREATE TABLE item_pedido
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      NUMBER NOT NULL,
    produto_id     NUMBER NOT NULL,
    quantidade     NUMBER NOT NULL,
    preco_unitario NUMBER(10,2) NOT NULL,
    FOREIGN KEY (pedido_id) REFERENCES pedido (id),
    FOREIGN KEY (produto_id) REFERENCES produto (id)
);

CREATE TABLE assinatura
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  NUMBER NOT NULL,
    data_inicio DATE    DEFAULT CURRENT_DATE,
    plano       VARCHAR2(50),
    ativo       BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);
