CREATE TABLE pagamento
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metodo         VARCHAR2(20)  NOT NULL, -- Ex: PIX, CARTAO
    status         VARCHAR2(20) DEFAULT 'PENDENTE',
    valor          NUMBER(10, 2) NOT NULL,
    data_pagamento TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    pedido_id      NUMBER        NOT NULL,
    CONSTRAINT fk_pagamento_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (id)
);

CREATE TABLE cupom_desconto
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo     VARCHAR2(50)  NOT NULL UNIQUE,
    valor      NUMBER(10, 2) NOT NULL,
    validade   DATE          NOT NULL,
    ativo      CHAR(1)   DEFAULT 'S',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
